In [2]:
#Importing the dataset
import numpy as np
import pandas as pd

#Importing the dataset
dataset = pd.read_csv('Clean_Dataset.csv')

In [2]:
#Displaying the number of rows
print("Number of rows: ", len(dataset))

Number of rows:  300153


In [25]:
#Creating a new data set with 200000 rows which are randomly selected from the original dataset
new_dataset = dataset.sample(n=200000, random_state=1)

#Saving the new dataset to a csv file
new_dataset.to_csv('Flights.csv', index=False)



In [3]:
#Importing the dataset
dataset = pd.read_csv('Flights.csv')

#Displaying the number of rows
print("Number of rows: ", len(dataset))

Number of rows:  200000


In [4]:
#Displaying the first 5 rows
dataset.sample(5)

Unnamed: 0    airline   flight source_city departure_time  \
658         118531     Indigo  6E-6212   Bangalore        Morning   
34419        65234  Air_India   AI-633      Mumbai  Early_Morning   
144060       34366     Indigo  6E-2083       Delhi  Early_Morning   
144137       97354    Vistara   UK-812   Bangalore        Morning   
75762         1943     Indigo   6E-369       Delhi          Night   

              stops arrival_time destination_city    class  duration  \
658            zero      Morning          Chennai  Economy      1.08   
34419   two_or_more        Night          Kolkata  Economy     16.58   
144060          one    Afternoon        Hyderabad  Economy      7.17   
144137          one        Night           Mumbai  Economy     11.50   
75762           one      Morning           Mumbai  Economy     10.42   

        days_left  price  
658            37   1604  
34419          22   6661  
144060         43   3457  
144137         20   7212  
75762          12   5955

In [5]:
#Removing the index column from the dataset named 'index'
dataset = dataset.drop(['Unnamed: 0'], axis=1)

In [6]:
#Dropping the flight column
dataset = dataset.drop(['flight'], axis=1)

In [7]:
dataset.head()

airline source_city departure_time stops   arrival_time destination_city  \
0  Air_India     Kolkata          Night   one        Morning           Mumbai   
1     Indigo   Bangalore      Afternoon   one        Evening           Mumbai   
2    AirAsia      Mumbai          Night   one  Early_Morning          Kolkata   
3     Indigo      Mumbai        Morning   one        Evening          Chennai   
4    Vistara   Bangalore          Night   one        Morning        Hyderabad   

      class  duration  days_left  price  
0   Economy     13.67         49   6048  
1   Economy      6.08         11  13421  
2   Economy      8.25         23   2836  
3   Economy      5.08         43   1890  
4  Business     12.50         31  56588

In [8]:
#Displaying the unique values in the airline column
print(dataset['airline'].unique())
#Displaying the unique values in the source_city column
print(dataset['source_city'].unique())
#Displaying the unique values in the destination_city column
print(dataset['destination_city'].unique())
#Displaying the unique values in the class column
print(dataset['class'].unique())
#Displaying the unique values in the departure_time column
print(dataset['departure_time'].unique())
#Displaying the unique values in the arrival_time column
print(dataset['arrival_time'].unique())
#Displaying the unique values in the stop column
print(dataset['stops'].unique())


['Air_India' 'Indigo' 'AirAsia' 'Vistara' 'SpiceJet' 'GO_FIRST']
['Kolkata' 'Bangalore' 'Mumbai' 'Delhi' 'Hyderabad' 'Chennai']
['Mumbai' 'Kolkata' 'Chennai' 'Hyderabad' 'Delhi' 'Bangalore']
['Economy' 'Business']
['Night' 'Afternoon' 'Morning' 'Early_Morning' 'Evening' 'Late_Night']
['Morning' 'Evening' 'Early_Morning' 'Afternoon' 'Late_Night' 'Night']
['one' 'zero' 'two_or_more']


In [11]:
import sklearn

In [13]:
#Regression algortihms

#Linear Regression
from sklearn.linear_model import LinearRegression
#Decision Tree Regression
from sklearn.tree import DecisionTreeRegressor
#Support Vector Regression
from sklearn.svm import SVR
#K-Nearest Neighbors Regression
from sklearn.neighbors import KNeighborsRegressor
#Gradient Boosting Regression
from sklearn.ensemble import GradientBoostingRegressor
#XGBoost Regression
from xgboost import XGBRegressor


In [14]:
#Train Test Split
from sklearn.model_selection import train_test_split

In [15]:
#Manually encoding the categorical variables
#['Air_India' 'Indigo' 'AirAsia' 'Vistara' 'SpiceJet' 'GO_FIRST']
#['AI-770' '6E-161' 'I5-330' ... 'SG-8480' 'SG-8106' '6E-5047']
#['Kolkata' 'Bangalore' 'Mumbai' 'Delhi' 'Hyderabad' 'Chennai']
#['Mumbai' 'Kolkata' 'Chennai' 'Hyderabad' 'Delhi' 'Bangalore']
#['Economy' 'Business']
#'Morning' 'Evening' 'Early_Morning' 'Afternoon' 'Late_Night' 'Night'
#['one' 'zero' 'two_or_more']
#Creating a dictionary for the airline column in alphabetical order
airline_dict = {'Air_India': 0, 'AirAsia': 1, 'GO_FIRST': 2, 'Indigo': 3, 'SpiceJet': 4, 'Vistara': 5}
#Creating a dictionary for the source_city column in alphabetical order
source_city_dict = {'Bangalore': 0, 'Chennai': 1, 'Delhi': 2, 'Hyderabad': 3, 'Kolkata': 4, 'Mumbai': 5}
#Creating a dictionary for the destination_city column in alphabetical order
destination_city_dict = {'Bangalore': 0, 'Chennai': 1, 'Delhi': 2, 'Hyderabad': 3, 'Kolkata': 4, 'Mumbai': 5}
#Creating a dictionary for the class column in alphabetical order
class_dict = {'Business': 0, 'Economy': 1}
#Creating a dictionary for the departure_time column in alphabetical order
departure_time_dict = {'Early_Morning': 0, 'Morning': 1, 'Afternoon': 2, 'Evening': 3, 'Night': 4, 'Late_Night': 5}
#Creating a dictionary for the arrival_time column in alphabetical order
arrival_time_dict = {'Early_Morning': 0, 'Morning': 1, 'Afternoon': 2, 'Evening': 3, 'Night': 4, 'Late_Night': 5}
#Creating a dictionary for the stops column in alphabetical order
stops_dict = {'zero': 0, 'one': 1, 'two_or_more': 2}

#Replacing the categorical values with the corresponding numerical values
dataset['airline'] = dataset['airline'].map(airline_dict)
dataset['source_city'] = dataset['source_city'].map(source_city_dict)
dataset['destination_city'] = dataset['destination_city'].map(destination_city_dict)
dataset['class'] = dataset['class'].map(class_dict)
dataset['departure_time'] = dataset['departure_time'].map(departure_time_dict)
dataset['arrival_time'] = dataset['arrival_time'].map(arrival_time_dict)
dataset['stops'] = dataset['stops'].map(stops_dict)

#Displaying the first 5 rows
dataset.head()





airline  source_city  departure_time  stops  arrival_time  \
0        0            4               4      1             1   
1        3            0               2      1             3   
2        1            5               4      1             0   
3        3            5               1      1             3   
4        5            0               4      1             1   

   destination_city  class  duration  days_left  price  
0                 5      1     13.67         49   6048  
1                 5      1      6.08         11  13421  
2                 4      1      8.25         23   2836  
3                 1      1      5.08         43   1890  
4                 3      0     12.50         31  56588

airline, source_city, destination_city, class, stops, departure_time, arrival_time, duration,days_left

In [16]:
#Rounding the duration colum to nearest integer and converting it to int
dataset['duration'] = dataset['duration'].round().astype(int)
dataset.head()

airline  source_city  departure_time  stops  arrival_time  \
0        0            4               4      1             1   
1        3            0               2      1             3   
2        1            5               4      1             0   
3        3            5               1      1             3   
4        5            0               4      1             1   

   destination_city  class  duration  days_left  price  
0                 5      1        14         49   6048  
1                 5      1         6         11  13421  
2                 4      1         8         23   2836  
3                 1      1         5         43   1890  
4                 3      0        12         31  56588

In [17]:
#Splitting the dataset into the training set and test set
X_train, X_test, y_train, y_test = train_test_split(dataset.drop(['price'], axis=1), dataset['price'], test_size=0.2, random_state=0)
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [18]:
models = {}

models["KNeighborsRegressor"]={"model":KNeighborsRegressor(n_neighbors=50)}
models["LinearRegression"]={"model":LinearRegression()}
models["XGBRegressor"]={"model":XGBRegressor(n_jobs=5,learning_rate=0.1,max_depth=10,random_state=1)}
models['GradientBoostingRegressor'] = {'model':GradientBoostingRegressor(n_estimators=50,max_depth=10)}
#models['RandomForestRegressor'] = {'model':RandomForestRegressor(n_estimators=50,max_depth=10)}

X= dataset.drop(['price'], axis=1)
y= dataset['price']

In [19]:
cv = KFold(n_splits=5)
for key,item in models.items():
    reg_model = item['model']
    print(item['model'])
    score = cross_val_score(estimator=reg_model,X = X,y = y,cv=cv,scoring='r2')
    print(score)

KNeighborsRegressor(n_neighbors=50)
[0.5026559  0.49998058 0.50394049 0.49987748 0.50306309]
LinearRegression()
[0.90665465 0.90800265 0.90650802 0.90747319 0.9060144 ]
XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.1, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=10, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=5, num_parallel_tree=None, predictor=None,
             random_state=1, ...)
[0.977268   0.97921133 0.97761658 0.97728295 0.97767696]
GradientBoostingRegressor(max_depth=10, n_

In [20]:
reg_model.fit(X_train, y_train)

GradientBoostingRegressor(max_depth=10, n_estimators=50)

In [21]:
reg_model.score(X_test, y_test)

0.973848443459414

In [22]:
#Saving the model
import pickle
pickle.dump(reg_model, open('flight_model.pkl','wb'))

In [23]:
# Saving the model as joblib
import joblib
joblib.dump(reg_model, 'flight_model.joblib')

['flight_model.joblib']

In [24]:
# Importing the model
model = pickle.load(open('flight_model.pkl','rb'))

In [27]:
import warnings
warnings.filterwarnings('ignore')
# Predicting the price of the flight
model.predict([[0, 1, 4, 5, 1, 1, 2, 3, 1]])

array([12390.10636429])

# Version 2.0 of the Model Preparation Notebook for the Flight Price Prediction Project

Creating a model using the Gradient Boosting Regressor algorithm to predict the price of a flight ticket.

Creating a model using modeling pipeline

In [140]:
# Importing the libraries
import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
import pickle
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import FeatureUnion
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
import pickle

In [164]:
# Importing the dataset
dataset_master = pd.read_csv('Flights.csv')

In [165]:
dataset = dataset_master.copy()

In [166]:
dataset.head()

index    airline     flight source_city departure_time stops  \
0  135562  Air_India     AI-770     Kolkata          Night   one   
1   95636     Indigo  6.00E-161   Bangalore      Afternoon   one   
2   65269    AirAsia     I5-330      Mumbai          Night   one   
3   83129     Indigo    6E-5214      Mumbai        Morning   one   
4  257806    Vistara     UK-814   Bangalore          Night   one   

    arrival_time destination_city     class  duration  days_left  price  
0        Morning           Mumbai   Economy     13.67         49   6048  
1        Evening           Mumbai   Economy      6.08         11  13421  
2  Early_Morning          Kolkata   Economy      8.25         23   2836  
3        Evening          Chennai   Economy      5.08         43   1890  
4        Morning        Hyderabad  Business     12.50         31  56588

In [167]:
dataset.drop(['index', 'flight'], axis=1, inplace=True)

In [168]:
dataset['duration'] = dataset['duration'].round().astype(int)

In [169]:
#Checking for null values
dataset.isnull().sum()

airline             0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
dtype: int64

In [170]:
dataset.head()

airline source_city departure_time stops   arrival_time destination_city  \
0  Air_India     Kolkata          Night   one        Morning           Mumbai   
1     Indigo   Bangalore      Afternoon   one        Evening           Mumbai   
2    AirAsia      Mumbai          Night   one  Early_Morning          Kolkata   
3     Indigo      Mumbai        Morning   one        Evening          Chennai   
4    Vistara   Bangalore          Night   one        Morning        Hyderabad   

      class  duration  days_left  price  
0   Economy        14         49   6048  
1   Economy         6         11  13421  
2   Economy         8         23   2836  
3   Economy         5         43   1890  
4  Business        12         31  56588

In [171]:
# Splitting the dataset into the Training set and Test set
X = dataset.drop(['price'], axis=1)
y = dataset['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [172]:
X_train.head()

airline source_city departure_time stops arrival_time  \
127478    Vistara   Bangalore  Early_Morning   one        Night   
155552  Air_India       Delhi        Evening   one        Night   
75475      Indigo   Hyderabad      Afternoon   one        Night   
186114  Air_India     Kolkata      Afternoon   one    Afternoon   
93717     Vistara     Chennai          Night   one      Morning   

       destination_city    class  duration  days_left  
127478           Mumbai  Economy        13         26  
155552          Kolkata  Economy        29         43  
75475           Chennai  Economy         9         22  
186114        Bangalore  Economy        23          6  
93717           Kolkata  Economy        12         13

In [173]:
y_train.head()

127478     7212
155552     4933
75475     12118
186114    13524
93717     11069
Name: price, dtype: int64

In [177]:
# DataFramesSelector class to select a subset of the Pandas DataFrame columns
def build_model(X_train, y_train, X_test, y_test):

    class DataFrameSelector(BaseEstimator, TransformerMixin):
        def __init__(self, attribute_names):
            self.attribute_names = attribute_names
        def fit(self, X, y=None):
            return self
        def transform(self, X):
            return X[self.attribute_names].values

    nums = list(X_train.select_dtypes(include=[np.number]).columns)
    cats = list(X_train.select_dtypes(include=[object]).columns)

    num_pipeline = Pipeline([
        ('selector', DataFrameSelector(nums)),
        ('std_scaler', StandardScaler()),
    ])

    cat_pipeline = Pipeline([
        ('selector', DataFrameSelector(cats)),
        ('cat_encoder', OneHotEncoder(sparse=False)),
    ])

    full_pipeline = FeatureUnion(transformer_list=[
        ("num_pipeline", num_pipeline),
        ("cat_pipeline", cat_pipeline),
    ])

    X_train_prepared = full_pipeline.fit_transform(X_train)
    X_test_prepared = full_pipeline.transform(X_test)

    return X_train_prepared, X_test_prepared, y_train, y_test

In [178]:
X_train_prepared, X_test_prepared, y_train, y_test = build_model(X_train, y_train, X_test, y_test)

In [176]:
# Fitting Gradient Boosting Regression to the dataset
regressor = GradientBoostingRegressor(n_estimators=50,max_depth=10)
regressor.fit(X_train_prepared, y_train)

GradientBoostingRegressor(max_depth=10, n_estimators=50)

In [179]:
# Predicting the Test set results
y_pred = regressor.predict(X_test_prepared)

# Calculating the R2 Score
r2_score(y_test, y_pred)

0.9755223226456883

In [186]:
# Saving model
import joblib
joblib.dump(regressor, 'D:/EPITA/dsp/Flight_v2/dsp-project-dsp-flight/model/flight_model.pkl')

['D:/EPITA/dsp/Flight_v2/dsp-project-dsp-flight/model/flight_model.pkl']

In [187]:
# Loading model to compare the results
model = pickle.load(open('flight_model.pkl','rb'))

In [188]:
# Predicting the Test set results
y_pred = model.predict(X_test_prepared)
y_pred

array([44998.49309361, 48972.43447206,  7403.17391214, ...,
        8362.42268036,  2582.93118939,  5602.29725571])

In [208]:
model.predict(X_test_prepared[100].reshape(1,-1))[0]

8643.843563747216